spring:
  data:
    postgres:
      port: 5432
      host: localhost
      database: overreactive
      username: test
      password: test

  r2dbc:
    url: r2dbc:postgresql://localhost/overreactive
    username: test
    password: test