version: 2.1
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.4-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
        environment:
          POSTGRES_URL: postgresql://test@localhost/overreactive
          POSTGRES_USER: test
          PGPASSWORD: test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_DB: overreactive
          POSTGRES_USER: test
          POSTGRES_PASS: test
    steps:
      - checkout # check out the code in the project directory
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: |
          psql -a -d $POSTGRES_URL -U $POSTGRES_USER -f "src/main/resources/db/schema.sql"
      - run: |
          psql -a -d $POSTGRES_URL -U $POSTGRES_USER -f "src/main/resources/db/data.sql"
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew clean build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: build/reports/tests
      - run: ./gradlew assemble
      - store_artifacts:
          path: build/libs
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
workflows:
  version: 2
  workflow:
    jobs:
      - build